ApplicationName.MVC/Controllers/AccountController.cs
using System.Security.Claims;
using ApplicationName.Domain.Models.Auth;
using ApplicationName.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApplicationName.MVC.Controllers;

public class AccountController : Controller
{
    private readonly ApplicationDbContext _context;

    public AccountController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register(Register model)
    {
        if (ModelState.IsValid)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u != null && u.Email == model.Email);
            if (user == null)
            {
                user = new User 
                    {
                        Email = model.Email, 
                        Password = model.Password,
                        Role = "User"
                    };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                await Authenticate(user);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Incorrect login and/or password");
        }

        return View(model);
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult Login()
    {
        return View();
    }
    
    public IActionResult Logout()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> LogoutD()
    {
        await HttpContext.SignOutAsync("Cookies");
        return RedirectToAction("Login", "Account");
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(Login model)
    {
        if (ModelState.IsValid)
        {
            var user = await _context.Users
                
                .FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
            if (user != null)
            {
                await Authenticate(user);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Incorrect login and/or password");
        }

        return View(model);
    }

    private async Task Authenticate(User? user)
    {
        if (user.Role != null)
        {
            var claims = new List<Claim>
            {
                new(ClaimsIdentity.DefaultNameClaimType, user.Email),
                new(ClaimsIdentity.DefaultRoleClaimType, user.Role)
            };

            var id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
    }
}

ApplicationName.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ApplicationName.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Card()
        {
            return View();
        }
        public ActionResult Checkout()
        {
            return View();
        }
        public ActionResult Shop()
        {
            return View();
        }
        public ActionResult Product_details()
        {
            return View();
        }
    }
}

ApplicationName.MVC/Controllers/ItemsController.cs
using ApplicationName.Domain.Models;
using ApplicationName.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;

namespace ApplicationName.MVC.Controllers;

[DisableCors]
[Authorize(Roles = "Administrator")]
public class ItemsController : Controller
{
    private readonly ApplicationDbContext? _db;

    public ItemsController(ApplicationDbContext? db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var objBookList = _db?.Items.ToList();
        return View(objBookList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Item obj)
    {
        _db?.Items.Add(obj);
        _db?.SaveChanges();
        return RedirectToAction("Index");
    }
    
    public IActionResult Delete(Guid? id)
    {
        var bookFromDb = _db.Items.Find(id);

        if (bookFromDb == null) return NotFound();

        return View(bookFromDb);
    }

    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(Guid? id)
    {
        var obj = _db.Items.Find(id);
        if (obj == null) return NotFound();

        _db.Items.Remove(obj);
        _db.SaveChanges();
        TempData["success"] = "Book deleted successfully";
        return RedirectToAction("Index");
    }
}

ApplicationName.MVC/Views/Home/Card.cshtml
@{
    ViewBag.Title = "Card";
}

<div class="cart_area section_padding_100 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="cart-table clearfix">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="cart_product_img d-flex align-items-center">
                                    <a href="#"><img src="~/fonts/img/product-img/product-9.jpg" alt="Product"></a>
                                    <h6>Yellow Cocktail Dress</h6>
                                </td>
                                <td class="price"><span>$49.88</span></td>
                                <td class="qty">
                                    <div class="quantity">
                                        <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                        <input type="number" class="qty-text" id="qty" step="1" min="1" max="99" name="quantity" value="1">
                                        <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                    </div>
                                </td>
                                <td class="total_price"><span>$49.88</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="cart-footer d-flex mt-30">
                    <div class="back-to-shop w-50">
                        <a href="shop-grid-left-sidebar.html">Continue shooping</a>
                    </div>
                    <div class="update-checkout w-50 text-right">
                        <a href="#">clear cart</a>
                        <a href="#">Update cart</a>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="coupon-code-area mt-70">
                    <div class="cart-page-heading">
                        <h5>Cupon code</h5>
                        <p>Enter your cupone code</p>
                    </div>
                    <form action="#">
                        <input type="search" name="search" placeholder="#569ab15">
                        <button type="submit">Apply</button>
                    </form>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="shipping-method-area mt-70">
                    <div class="cart-page-heading">
                        <h5>Shipping method</h5>
                        <p>Select the one you want</p>
                    </div>

                    <div class="custom-control custom-radio mb-30">
                        <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
                        <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio1"><span>Next day delivery</span><span>$4.99</span></label>
                    </div>

                    <div class="custom-control custom-radio mb-30">
                        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                        <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio2"><span>Standard delivery</span><span>$1.99</span></label>
                    </div>

                    <div class="custom-control custom-radio">
                        <input type="radio" id="customRadio3" name="customRadio" class="custom-control-input">
                        <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio3"><span>Personal Pickup</span><span>Free</span></label>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="cart-total-area mt-70">
                    <div class="cart-page-heading">
                        <h5>Cart total</h5>
                        <p>Final info</p>
                    </div>

                    <ul class="cart-total-chart">
                        <li><span>Subtotal</span> <span>$59.90</span></li>
                        <li><span>Shipping</span> <span>Free</span></li>
                        <li><span><strong>Total</strong></span> <span><strong>$59.90</strong></span></li>
                    </ul>
                    <a href="@Url.Action("Checkout")" class="btn karl-checkout-btn">Proceed to checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

ApplicationName.MVC/Views/Home/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
}


<!-- ****** Checkout Area Start ****** -->
<div class="checkout_area section_padding_100">
    <div class="container">
        <div class="row">

            <div class="col-12 col-md-6">
                <div class="checkout_details_area mt-50 clearfix">

                    <div class="cart-page-heading">
                        <h5>Billing Address</h5>
                        <p>Enter your cupone code</p>
                    </div>

                    <form action="#" method="post">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="first_name">First Name <span>*</span></label>
                                <input type="text" class="form-control" id="first_name" value="" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="last_name">Last Name <span>*</span></label>
                                <input type="text" class="form-control" id="last_name" value="" required>
                            </div>
                            <div class="col-12 mb-3">
                                <label for="company">Company Name</label>
                                <input type="text" class="form-control" id="company" value="">
                            </div>
                            <div class="col-12 mb-3">
                                <label for="country">Country <span>*</span></label>
                                <select class="custom-select d-block w-100" id="country">
                                    <option value="usa">United States</option>
                                    <option value="uk">United Kingdom</option>
                                    <option value="ger">Germany</option>
                                    <option value="fra">France</option>
                                    <option value="ind">India</option>
                                    <option value="aus">Australia</option>
                                    <option value="bra">Brazil</option>
                                    <option value="cana">Canada</option>
                                </select>
                            </div>
                            <div class="col-12 mb-3">
                                <label for="street_address">Address <span>*</span></label>
                                <input type="text" class="form-control mb-3" id="street_address" value="">
                                <input type="text" class="form-control" id="street_address2" value="">
                            </div>
                            <div class="col-12 mb-3">
                                <label for="postcode">Postcode <span>*</span></label>
                                <input type="text" class="form-control" id="postcode" value="">
                            </div>
                            <div class="col-12 mb-3">
                                <label for="city">Town/City <span>*</span></label>
                                <input type="text" class="form-control" id="city" value="">
                            </div>
                            <div class="col-12 mb-3">
                                <label for="state">Province <span>*</span></label>
                                <input type="text" class="form-control" id="state" value="">
                            </div>
                            <div class="col-12 mb-3">
                                <label for="phone_number">Phone No <span>*</span></label>
                                <input type="number" class="form-control" id="phone_number" min="0" value="">
                            </div>
                            <div class="col-12 mb-4">
                                <label for="email_address">Email Address <span>*</span></label>
                                <input type="email" class="form-control" id="email_address" value="">
                            </div>

                            <div class="col-12">
                                <div class="custom-control custom-checkbox d-block mb-2">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Terms and conitions</label>
                                </div>
                                <div class="custom-control custom-checkbox d-block mb-2">
                                    <input type="checkbox" class="custom-control-input" id="customCheck2">
                                    <label class="custom-control-label" for="customCheck2">Create an accout</label>
                                </div>
                                <div class="custom-control custom-checkbox d-block">
                                    <input type="checkbox" class="custom-control-input" id="customCheck3">
                                    <label class="custom-control-label" for="customCheck3">Subscribe to our newsletter</label>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-5 ml-lg-auto">
                <div class="order-details-confirmation">

                    <div class="cart-page-heading">
                        <h5>Your Order</h5>
                        <p>The Details</p>
                    </div>

                    <ul class="order-details-form mb-4">
                        <li><span>Product</span> <span>Total</span></li>
                        <li><span>Cocktail Yellow dress</span> <span>$59.90</span></li>
                        <li><span>Subtotal</span> <span>$59.90</span></li>
                        <li><span>Shipping</span> <span>Free</span></li>
                        <li><span>Total</span> <span>$59.90</span></li>
                    </ul>


                    <div id="accordion" role="tablist" class="mb-4">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <h6 class="mb-0">
                                    <a data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne"><i class="fa fa-circle-o mr-3"></i>Paypal</a>
                                </h6>
                            </div>

                            <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                                <div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra tempor so dales. Phasellus sagittis auctor gravida. Integ er bibendum sodales arcu id te mpus. Ut consectetur lacus.</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingTwo">
                                <h6 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"><i class="fa fa-circle-o mr-3"></i>cash on delievery</a>
                                </h6>
                            </div>
                            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                                <div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo quis in veritatis officia inventore, tempore provident dignissimos.</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingThree">
                                <h6 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"><i class="fa fa-circle-o mr-3"></i>credit card</a>
                                </h6>
                            </div>
                            <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
                                <div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse quo sint repudiandae suscipit ab soluta delectus voluptate, vero vitae</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingFour">
                                <h6 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour"><i class="fa fa-circle-o mr-3"></i>direct bank transfer</a>
                                </h6>
                            </div>
                            <div id="collapseFour" class="collapse show" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
                                <div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est cum autem eveniet saepe fugit, impedit magni.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="#" class="btn karl-checkout-btn">Place Order</a>
                </div>
            </div>

        </div>
    </div>
</div>

ApplicationName.MVC/Views/Items/Create.cshtml
@model ApplicationName.Domain.Models.Item

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Item</h2>
            <hr/>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control"/>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Add new Item</button>
        <a asp-controller="Items" asp-action="Create" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

ApplicationName.MVC/Views/Items/Delete.cshtml
@model ApplicationName.Domain.Models.Item

<div class="align-content-xxl-center">
    <form method="post" asp-action="Delete">
        <input asp-for="Id" hidden/>
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary">Delete?</h2>
                <hr/>
            </div>
            <div class="mb-3">
                <label hidden asp-for="Name"></label>
                <input hidden asp-for="Name" disabled class="form-control"/>
            </div>
            <div class="mb-3">
                <label hidden asp-for="Price"></label>
                <input hidden asp-for="Price" disabled class="form-control"/>
            </div>
            <button type="submit" class="btn btn-danger" style="width:150px">Delete!</button>
            <a asp-controller="Items" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back :(
            </a>
        </div>
    </form>
</div>

ApplicationName.MVC/Views/Items/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Item";
    Layout = "_Layout";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Items" asp-action="Create" class="btn btn-primary"> <i class="bi bi-file-earmark-plus-fill"></i> Add new</a>
        </div>
        <br/>
    </div>

    <table class="table table-bordered table-striped" style="width: 100%; margin-top: 20px">
        <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                 Name
            </th>
            <th>
                Price
                </th>


        </tr>
        </thead>
        <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>
                    @obj.Id
                </td>
                <td>
                    @obj.Name
                </td>
                <td>
                    @obj.Price
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Items" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-1">
                            <i class="bi bi-trash-fill"></i> Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

ApplicationName.MVC/Views/Shared/_Header.cshtml
<header class="header_area">
    <!-- Top Header Area Start -->
    <div class="top_header_area">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-end">

                <div class="col-12 col-lg-7">
                    <div class="top_single_area d-flex align-items-center">
                        <!-- Logo Area -->
                        <div class="top_logo">
                            <a href="#"> <img src="~/img/core-img/logo.png" alt=""> </a>
                        </div>
                        <!-- Cart & Menu Area -->
                        <div class="header-cart-menu d-flex align-items-center ml-auto">
                            <!-- Cart Area -->
                            <div class="cart">
                                <a href="#" id="header-cart-btn" target="_blank">
                                    <span class="cart_quantity"> 2</span>
                                    <i class="ti-bag"> </i> Your Bag $20
                                </a>
                                <!-- Cart List Area Start -->
                                <ul class="cart-list">
                                    <li>
                                        <a href="#" class="image"> <img src="~/fonts/img/product-img/product-10.jpg" class="cart-thumb" alt=""> </a>
                                        <div class="cart-item-desc">
                                            <h6> <a href="#"> Women's Fashion</a></h6>
                                            <p> 1x - <span class="price"> $10</span> </p>
                                        </div>
                                        <span class="dropdown-product-remove"> <i class="icon-cross"> </i> </span>
                                    </li>
                                    <li>
                                        <a href="#" class="image"> <img src="~/fonts/img/product-img/product-11.jpg" class="cart-thumb" alt=""> </a>
                                        <div class="cart-item-desc">
                                            <h6> <a href="#"> Women's Fashion</a></h6>
                                            <p> 1x - <span class="price"> $10</span> </p>
                                        </div>
                                        <span class="dropdown-product-remove"> <i class="icon-cross"> </i> </span>
                                    </li>
                                    <li class="total">
                                        <span class="pull-right"> Total: $20.00</span>
                                        <a href="cart.html" class="btn btn-sm btn-cart"> Cart</a>
                                        <a href="checkout-1.html" class="btn btn-sm btn-checkout"> Checkout</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="header-right-side-menu ml-15">
                                <a href="#" id="sideMenuBtn"> <i class="ti-menu" aria-hidden="true"> </i> </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Top Header Area End -->
    <div class="main_header_area">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-12 d-md-flex justify-content-between">
                    <!-- Header Social Area -->
                    <div class="header-social-area">
                        <a href="#"> <span class="karl-level"> Share</span> <i class="fa fa-pinterest" aria-hidden="true"> </i> </a>
                        <a href="#"> <i class="fa fa-facebook" aria-hidden="true"> </i> </a>
                        <a href="#"> <i class="fa fa-twitter" aria-hidden="true"> </i> </a>
                        <a href="#"> <i class="fa fa-linkedin" aria-hidden="true"> </i> </a>
                    </div>
                    <!-- Menu Area -->
                    <div class="main-menu-area">
                        <nav class="navbar navbar-expand-lg align-items-start">

                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#karl-navbar" aria-controls="karl-navbar" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"> <i class="ti-menu"> </i> </span> </button>

                            <div class="collapse navbar-collapse align-items-start collapse" id="karl-navbar">
                                <ul class="navbar-nav animated" id="nav">
                                    <li class="nav-item active"> <a class="nav-link" asp-action="Index" asp-controller="Home"> Home</a> </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="karlDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Pages</a>
                                        <div class="dropdown-menu" aria-labelledby="karlDropdown">

                                            <a class="dropdown-item" asp-action="Shop" asp-controller="Home"> Shop</a>
                                            <a class="dropdown-item" asp-action="Product_details" asp-controller="Home"> Product Details</a>
                                            <a class="dropdown-item" asp-action="Card" asp-controller="Home"> Cart</a>
                                            <a class="dropdown-item" asp-action="Checkout" asp-controller="Home"> Checkout</a>
                                            <a class="dropdown-item" asp-action="Login" asp-controller="Account"> Login</a>
                                            <a class="dropdown-item" asp-action="Logout" asp-controller="Account"> Logout</a>
                                            <a class="dropdown-item" asp-action="Register" asp-controller="Account"> Register</a>
                                            <a class="dropdown-item" asp-action="Index" asp-controller="Items"> Index Admin</a>

                                        </div>
                                    </li>
                                    <li class="nav-item"> <a class="nav-link" asp-action="Index" asp-controller="Home"> Sign in</a> </li>
                                </ul>
                            </div>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>
</header>
<section class="top-discount-area d-md-flex align-items-center">
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5> Free Shipping &amp; Returns</h5>
        <h6> <a href="#"> BUY NOW</a> </h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5> 20% Discount for all dresses</h5>
        <h6> USE CODE: Colorlib</h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5> 20% Discount for students</h5>
        <h6> USE CODE: Colorlib</h6>
    </div>
</section>